---
name: MQTT IO
version: 24.09.01-1
slug: mqtt-io
description: Expose GPIO modules and digital sensors via MQTT for remote control and monitoring.
url: https://github.com/tirasol/addon-mqtt-io
codenotary: ceo@tabspace.kr
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
full_access: true
privileged:
  - SYS_RAWIO
map:
  - config:rw
  - share:rw
  - ssl
options:
  configuration_file: /config/mqtt-io/config.yaml
schema:
  configuration_file: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
